### ISSUE TITLE
Implement an URI parser

### ISSUE THREAD

**Issue by yuriy-yarosh** [bitsnap/bitsnap#3]
`src/http/URI.scala` should be improved a bit and needs some testing.

**Comment by P3trur0** [comment]
Do you mean something like transform [this](https://github.com/bitsnap/bitsnap/blob/master/src/http/URI.scala#L129) to a case class, for example?

**Comment by yuriy-yarosh** [comment]
@P3trur0 yup.

**Comment by P3trur0** [comment]
@yuriy-yarosh if you like I can go with this, then.

**Comment by yuriy-yarosh** [comment]
Sure thing, P3trur0, I've sent an invite.
Apply, and I'll assign it to you.

**Comment by P3trur0** [comment]
@yuriy-yarosh here I am. I'll start to work on it this evening. Is it ok?

**Comment by yuriy-yarosh** [comment]
@P3trur0 feel free to do it whenever you want to.
Please use `scalafmt` / `scalastyle` for code formatting.
Poke me on [gitter](https://gitter.im/bitsnap/general) if you'll get any questions or suggestions.

**Comment by P3trur0** [comment]
@yuriy-yarosh I'll go with `scalafmt`

**Comment by oschrenk** [comment]
This can be closed as #7 is merged?

**Comment by yuriy-yarosh** [comment]
@oschrenk yup yup, I'm just to busy even to close it.
Sorry for bothering.
